import 'package:flutter/material.dart';

class ColorTheme {
  static ColorScheme get light => const ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff2e4caa),
        onPrimary: Color(0xffffffff),
        primaryContainer: Color(0xff2e4caa),
        onPrimaryContainer: Color(0xff111013),
        secondary: Color(0xffe5b20e),
        onSecondary: Color(0xff000000),
        error: Color(0xffb00020),
        onError: Color(0xffffffff),
        background: Color(0xfff8f7fb),
        onBackground: Color(0xff090909),
        surface: Color(0xfff8f7fb),
        onSurface: Color(0xff090909),
        // secondaryContainer: Color(0xff9fcbf1),
        // onSecondaryContainer: Color(0xff0e1114),
        // tertiary: Color(0xff0091ea),
        // onTertiary: Color(0xffffffff),
        // tertiaryContainer: Color(0xffcfe4ff),
        // onTertiaryContainer: Color(0xff111314),
        // errorContainer: Color(0xfffcd8df),
        // onErrorContainer: Color(0xff141213),
        // surfaceVariant: Color(0xfff1eff8),
        // onSurfaceVariant: Color(0xff121213),
        // outline: Color(0xff565656),
        // shadow: Color(0xff000000),
        // inverseSurface: Color(0xff121116),
        // onInverseSurface: Color(0xfff5f5f5),
        // inversePrimary: Color(0xffd1c0ff),
        // surfaceTint: Color(0xff4527a0),
      );

  static ColorScheme get dark => const ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xff2e4caa),
        onPrimary: Color(0xffffffff),
        primaryContainer: Color(0xff2e4caa),
        onPrimaryContainer: Color(0xff111013),
        secondary: Color(0xffff21f4),
        onSecondary: Color(0xff000000),
        error: Color(0xffb00020),
        onError: Color(0xffffffff),
        background: Color(0xff0e1221),
        onBackground: Color(0xffffffff),
        surface: Color(0xffffffff),
        onSurface: Color(0xffff21f4),
        // secondaryContainer: Color(0xff9fcbf1),
        // onSecondaryContainer: Color(0xff0e1114),
        // tertiary: Color(0xff0091ea),
        // onTertiary: Color(0xffffffff),
        // tertiaryContainer: Color(0xffcfe4ff),
        // onTertiaryContainer: Color(0xff111314),
        // errorContainer: Color(0xfffcd8df),
        // onErrorContainer: Color(0xff141213),
        // surfaceVariant: Color(0xfff1eff8),
        // onSurfaceVariant: Color(0xff121213),
        // outline: Color(0xff565656),
        // shadow: Color(0xff000000),
        // inverseSurface: Color(0xff121116),
        // onInverseSurface: Color(0xfff5f5f5),
        // inversePrimary: Color(0xffd1c0ff),
        // surfaceTint: Color(0xff4527a0),
      );
}
