name: dice_and_die_flutter
description: This is a board game whit dice and strategy.
publish_to: 'none'

version: 1.1.1+31

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dart_code_metrics: ^5.7.6
  l: ^4.0.2
  injectable_generator: ^2.4.1
  injectable: ^2.3.2
  dio: ^5.3.0
  dio_intercept_to_curl: ^0.1.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  auto_route: ^7.8.4
  gap: ^3.0.1
  get_it: ^7.6.4
  cupertino_icons: ^1.0.6
  web_socket_channel: ^2.4.0
  uuid: ^3.0.0
  google_fonts: ^4.0.3
  flutter_launcher_icons: ^0.13.1
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.2
  reactive_forms: ^16.1.1
  flutter_speed_dial: ^7.0.0




dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner:
  auto_route_generator: ^7.3.2
  flutter_test:
    sdk: flutter

  lint: ^2.3.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/app_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app_logo.png"

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/emotes/
    - assets/sounds/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
